version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - norskball-network
    depends_on:
      - frontend
      - backend

  frontend:
    image: ${DOCKERHUB_USERNAME}/norskball-frontend:latest
    networks:
      - norskball-network

  backend:
    image: ${DOCKERHUB_USERNAME}/norskball-backend:latest
    networks:
      - norskball-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email wangen93@gmail.com -d norskball.duckdns.org --agree-tos --non-interactive --force-renewal
    depends_on:
      - nginx

networks:
  norskball-network:
    driver: bridge 