name: Deploy Norskball

on:
  push:
    branches: [ main ]

# Add permissions for the GitHub Actions bot
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: |
          cd backend/src/Norskball
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/norskball-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Generate GraphQL types
        run: |
          cd frontend
          yarn graphql-codegen

      - name: Build frontend
        run: |
          cd frontend
          VITE_API_BASE_URL=https://norskball-backend.onrender.com \
          VITE_API_TIMEOUT=10000 \
          VITE_TOKEN_EXPIRY_MINUTES=60 \
          VITE_REFRESH_TOKEN_EXPIRY_DAYS=7 \
          VITE_ENABLE_DARK_MODE=true \
          VITE_ENABLE_NOTIFICATIONS=true \
          VITE_DEFAULT_LANGUAGE=en \
          VITE_ITEMS_PER_PAGE=20 \
          VITE_LOG_LEVEL=info \
          VITE_ENABLE_CONSOLE_LOGGING=true \
          VITE_ENABLE_FILE_LOGGING=false \
          VITE_GOOGLE_CLIENT_ID=266076307059-pfaiq2uh5l0dnd0t3q5p8cs7s1i7ilk2.apps.googleusercontent.com \
          yarn build

      - name: Create CNAME file
        run: |
          cd frontend/dist/spa
          echo "norskball.no" > CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist/spa
          publish_branch: gh-pages
          commit_message: "Deploy frontend to GitHub Pages [skip ci]"