name: Deploy to Windows Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Docker Hub username
        run: echo "Docker Hub username: ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/norskball:backend-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: DOCKER_BUILDKIT=1

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/norskball:frontend-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: DOCKER_BUILDKIT=1

      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Norskball
            docker-compose pull
            docker-compose up -d 